version: '3'

services:
  hisat2:
    # use an image
    image: umeshwww/hisat2-preprocess:v0.0.1

    # or build locally...
    build: .

    # set the snakemake options with command
    command: "--jobs 8"

    volumes:
      - ./test/fastq-generated:/fastq:ro
      - ./test/index:/meta:rw
      - ./test/output:/output:rw

      # if necessary mount a config file (see config/config.yml for details)
      - ./config/config.yml:/config/config.yml:ro
